name: mask/map--form
typeName: mask_map__form
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
fields:
  -
    type: Textarea
    identifier: tx_mask_map_
    label: 'Map Iframe'
    wrap: virtual
  -
    type: Collection
    identifier: tx_mask_contact_detail
    label: 'Contact Detail'
    appearance:
      enabledControls:
        delete: true
        dragdrop: true
        hide: true
        info: true
        localize: true
        new: true
        sort: true
      levelLinksPosition: top
      showAllLocalizationLink: true
      showNewRecordLink: true
      showPossibleLocalizationRecords: true
      useSortable: true
    foreign_field: parentid
    foreign_sortby: sorting
    fields:
      -
        type: File
        identifier: tx_mask_image
        label: Icon
        appearance:
          elementBrowserEnabled: true
          enabledControls:
            delete: true
            dragdrop: true
            hide: true
            info: true
            localize: true
            sort: false
          fileUploadAllowed: true
          useSortable: true
        allowed: common-image-types
      -
        type: Text
        identifier: tx_mask_contact
        label: Contact
      -
        type: Text
        identifier: tx_mask_label
        label: Label
  -
    type: Collection
    identifier: tx_mask_form
    label: Form
    appearance:
      enabledControls:
        delete: true
        dragdrop: true
        hide: true
        info: true
        localize: true
        new: true
        sort: true
      levelLinksPosition: top
      showAllLocalizationLink: true
      showNewRecordLink: true
      showPossibleLocalizationRecords: true
      useSortable: true
    foreign_sortby: sorting
    foreign_table: tt_content
    overrideChildTca:
      columns: {  }
    foreign_field: tx_mask_content_parent_uid
    foreign_table_field: tx_mask_content_tablenames
    foreign_match_fields:
      tx_mask_content_role: tx_mask_form
    allowedRecordTypes:
      - form_formframework
