services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Aashro\AtVilla\EventListener\PackageActivationListener:
    tags:
      - name: event.Listener
        identifier: 'package.activation'